"""Shared domain layer — typed objects, adapter ABCs, and stub implementations."""

from .adapters import DataAdapter, ExecutionAdapter
from .exceptions import (
    AuditIncompleteError,
    DataIntegrityError,
    DataUnavailableError,
    ExecutionError,
    IncompleteDataError,
    InsufficientDataError,
    UnknownModelError,
    WeightSumError,
)
from .objects import (
    CRITICAL_SOURCES,
    DEGRADED_SOURCES,
    AuditRecord,
    DataQualityReport,
    EvaluationReport,
    ExecutionIntent,
    ExperimentParams,
    MarketDataset,
    MarketState,
    OHLCVBar,
    Order,
    RankedUniverse,
    RiskDecision,
    RunConfig,
    ScoreSet,
    SourceCriticality,
    TargetPortfolio,
    TickerData,
    TickerFeatures,
    Universe,
)
from .stubs import StubDataAdapter, StubExecutionAdapter

__all__ = [
    "RunConfig",
    "OHLCVBar",
    "TickerData",
    "TickerFeatures",
    "Order",
    "Universe",
    "MarketDataset",
    "MarketState",
    "ExperimentParams",
    "ScoreSet",
    "RankedUniverse",
    "TargetPortfolio",
    "RiskDecision",
    "ExecutionIntent",
    "EvaluationReport",
    "AuditRecord",
    "DataAdapter",
    "ExecutionAdapter",
    "StubDataAdapter",
    "StubExecutionAdapter",
    "DataUnavailableError",
    "DataIntegrityError",
    "IncompleteDataError",
    "InsufficientDataError",
    "UnknownModelError",
    "WeightSumError",
    "ExecutionError",
    "AuditIncompleteError",
    "DataQualityReport",
    "SourceCriticality",
    "CRITICAL_SOURCES",
    "DEGRADED_SOURCES",
]
